ALTER TABLE "Withdrawal" ADD COLUMN IF NOT EXISTS "grossRequested" DECIMAL(18,2);
ALTER TABLE "Withdrawal" ADD COLUMN IF NOT EXISTS "feeAmount" DECIMAL(18,2);
ALTER TABLE "Withdrawal" ADD COLUMN IF NOT EXISTS "charityAmount" DECIMAL(18,2);
ALTER TABLE "Withdrawal" ADD COLUMN IF NOT EXISTS "feePoolAmount" DECIMAL(18,2);
